version: '3'
services:
    db:
        image: mongo:4.4.1
    backend:
        image: node:10.16.3
        volumes:
            - ./backend:/backend
        ports:
            - 3000:3000
        command: bash -c "cd /backend && npm i && node app"
    frontend:
        image: nginx:1.19
        volumes:
            - ./frontend:/usr/share/nginx/html
        ports: 
            - 80:80
